version: '3.8'
services:
    database:
      image: postgres
      restart: always
      environment:
        - POSTGRES_DB=coolmeal
        - POSTGRES_USER=coolmeal
        - POSTGRES_PASSWORD=coolmeal
      container_name: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data/
      ports:
        - "5432:5432"
    pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
volumes:
  pgdata: null