version: '3.8'
services:
    database:
      image: postgres
      restart: on-failure
      environment:
        POSTGRES_DB: coolmeal
        POSTGRES_USER: shharw
        POSTGRES_PASSWORD: aHZf63WsfM
      container_name: postgres
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - "5555:5432"
    pgadmin:
      image: dpage/pgadmin4
      restart: on-failure
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
volumes:
  postgres: